### ISSUE TITLE
Error while editing a new file

### ISSUE THREAD

**Issue by aki237** [zachwhaley/eli#2]
While trying to edit a new file : 
```
Segmentation Fault Core Dumped
```

**Comment by zachwhaley** [comment]
Thanks for checking out my project :)

**Comment by aki237** [comment]
Still no change. Same Segmentation fault........
Probably there must be some fault in display function..... 
```void 
Buffer::display()
```

**Comment by zachwhaley** [comment]
I've noticed it crashes when you don't give eli a file name at all.  Is that what you are seeing?  Or does it still crash when you give eli file a file name that doesn't exist?

**Comment by aki237** [comment]
ya that's it

**Comment by zachwhaley** [comment]
Alright, I'll open a new bug

**Comment by zachwhaley** [comment]
Created #4 for the new issue
